[package]
name = "godot-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot-test_macros = { path = "../godot-test_macros"}
godot-test_defs = { path = "../godot-test_defs"}